/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package obelix;

import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;

import alex.AnalizadorLexicoAsterix;
import asint.AnalizadorSintacticoAsterix;
import errors.GestionErroresAsterix;

public class App {
    public static void main(String[] args) throws Exception {
        Reader input = new InputStreamReader(new FileInputStream(args[0]));
        AnalizadorLexicoAsterix alex = new AnalizadorLexicoAsterix(input);
        AnalizadorSintacticoAsterix asint = new AnalizadorSintacticoAsterix(alex);
        Object archivo = asint.parse().value;
        if (GestionErroresAsterix.numErroresSemanticos + GestionErroresAsterix.numErroresSintacticos == 0) {
            try (FileWriter file = new FileWriter(args[1])) {
                try {
                    file.write(archivo.toString());
                    file.flush();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            System.err.println("*** Errores en el código, no se genera salida.");
        }
    }
}
