
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Mar 12 18:34:06 CET 2022
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 46;
  public static final int FORIX = 43;
  public static final int POW = 35;
  public static final int MAIGUAL = 33;
  public static final int POT = 6;
  public static final int RET = 48;
  public static final int POTION = 45;
  public static final int MEIGUAL = 32;
  public static final int PANOR = 44;
  public static final int INTEGER = 11;
  public static final int PUNTOCOMA = 9;
  public static final int REF = 37;
  public static final int NOT = 36;
  public static final int BOOLIX = 3;
  public static final int AND = 29;
  public static final int IGUAL = 27;
  public static final int OR = 28;
  public static final int DIV = 26;
  public static final int DIS = 30;
  public static final int IF = 39;
  public static final int ID = 52;
  public static final int ENUMIX = 4;
  public static final int FLOATING = 12;
  public static final int EOF = 0;
  public static final int ROMANO = 14;
  public static final int ASIG = 31;
  public static final int error = 1;
  public static final int VECTIX = 7;
  public static final int MUL = 25;
  public static final int COMA = 10;
  public static final int INTIX = 2;
  public static final int MENOS = 24;
  public static final int MENOR = 15;
  public static final int MOD = 34;
  public static final int DATIX = 8;
  public static final int WHILIX = 41;
  public static final int PUNT = 38;
  public static final int MAYOR = 16;
  public static final int FLECHA = 47;
  public static final int LLC = 22;
  public static final int ELSE = 40;
  public static final int LLA = 21;
  public static final int STIL = 51;
  public static final int SKIP = 49;
  public static final int PUNTO = 42;
  public static final int TABEL = 50;
  public static final int PAC = 20;
  public static final int PAA = 19;
  public static final int CORC = 18;
  public static final int CORA = 17;
  public static final int FLOATIX = 5;
  public static final int GALO = 13;
  public static final int MAS = 23;
}

