
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int panor = 43;
  public static final int whilix = 40;
  public static final int mul = 25;
  public static final int mod = 34;
  public static final int flecha = 46;
  public static final int asig = 31;
  public static final int elset = 39;
  public static final int coma = 10;
  public static final int igual = 27;
  public static final int llc = 22;
  public static final int lla = 21;
  public static final int ift = 38;
  public static final int pac = 20;
  public static final int paa = 19;
  public static final int stil = 49;
  public static final int floating = 12;
  public static final int intix = 2;
  public static final int menos = 24;
  public static final int floatix = 5;
  public static final int menor = 15;
  public static final int EOF = 0;
  public static final int datix = 8;
  public static final int potion = 44;
  public static final int mas = 23;
  public static final int error = 1;
  public static final int maigual = 33;
  public static final int corc = 18;
  public static final int pow = 35;
  public static final int mayor = 16;
  public static final int cora = 17;
  public static final int or = 28;
  public static final int pot = 6;
  public static final int meigual = 32;
  public static final int ret = 47;
  public static final int punto = 41;
  public static final int tabel = 48;
  public static final int dospuntos = 45;
  public static final int galo = 13;
  public static final int integer = 11;
  public static final int id = 50;
  public static final int boolix = 3;
  public static final int ref = 37;
  public static final int not = 36;
  public static final int and = 29;
  public static final int puntocoma = 9;
  public static final int romano = 14;
  public static final int enumix = 4;
  public static final int div = 26;
  public static final int forix = 42;
  public static final int vectix = 7;
  public static final int dis = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "intix",
  "boolix",
  "enumix",
  "floatix",
  "pot",
  "vectix",
  "datix",
  "puntocoma",
  "coma",
  "integer",
  "floating",
  "galo",
  "romano",
  "menor",
  "mayor",
  "cora",
  "corc",
  "paa",
  "pac",
  "lla",
  "llc",
  "mas",
  "menos",
  "mul",
  "div",
  "igual",
  "or",
  "and",
  "dis",
  "asig",
  "meigual",
  "maigual",
  "mod",
  "pow",
  "not",
  "ref",
  "ift",
  "elset",
  "whilix",
  "punto",
  "forix",
  "panor",
  "potion",
  "dospuntos",
  "flecha",
  "ret",
  "tabel",
  "stil",
  "id"
  };
}

